name: "DEFAULT"

params:
  task:
    task: columbus
    env_name: Columbus-v1
    env_args:
      observable:
        - type: State
          coordsAgent: True
          speedAgent: True
          coordsRelativeToAgent: False
          coordsRewards: True
          coordsEnemys: False
          enemysNoBarriers: True
          rewardsTimeouts: False
          include_rand: True
        - type: State
          coordsAgent: False
          speedAgent: False
          coordsRelativeToAgent: True
          coordsRewards: True
          coordsEnemys: False
          enemysNoBarriers: True
          rewardsTimeouts: False
          include_rand: True
        - type: Compass
        - type: RayCast
          num_rays: 6
          chans: [Enemy]
      entities:
        - type: Ball
          radius: 16px
          pos: [0.8, 0.5]
          speed: [-0.2, -0.1]
          speed_rand: [0, 0.2]
          solid: True
          collision_elasticity: 3
          elasticity: 1
          movable: 1
          collision_changes_speed: True
          crash_conservation_of_energy: False
          min_speed: 0.2
          max_speed: 0.6
          draw_path: True
          draw_path_width: 32
          draw_path_harm: True
          drag: 0.00001
        - type: RectGoal # Good
          height: 1em
          width: 10ct
          pos: [97ct, 0ct]
          skip_agent_col_check: True
          col: [0, 255, 0]
          reward: 30
          solid: True
          elasticity: 0.6
          void_collidable: False
        - type: Goal # Top
          radius: 7ct
          pos: [100ct, 0ct]
          skip_agent_col_check: True
          col: [0, 255, 0]
          reward: 30
          solid: True
          elasticity: 0.7
          void_collidable: False
        - type: Goal # Bottom
          radius: 7ct
          pos: [100ct, 100ct]
          skip_agent_col_check: True
          col: [0, 255, 0]
          reward: 30
          solid: True
          elasticity: 0.7
          void_collidable: False
        - type: RectGoal # Bad
          height: 1em
          width: 3ct
          pos: [0ct, 0ct]
          skip_agent_col_check: True
          col: [255, 0, 0]
          reward: -45
          solid: True
          elasticity: 1000
          void_collidable: False
      agent_cls: PongAgent
      agent_attrs:
        height: 100
        width: 30
        movable: False
        solid: True
        elasticity: 0.9
      exception_for_unsupported_collision: False
      start_pos: [0.05, 0.5]
      start_score: 0
      speed_fac: 0.05
      acc_fac: 0.1
      die_on_zero: False #True
      agent_drag: 0
      controll_type: SPEED
      aux_reward_max: 0
      aux_penalty_max: 0
      void_damage: 0
      terminate_on_reward: False
      agent_draw_path: False
      clear_path_on_reset: False
---